# Translations template for keystone.
# Copyright (C) 2014 OpenStack Foundation
# This file is distributed under the same license as the keystone project.
#
# Translators:
msgid ""
msgstr ""
"Project-Id-Version: Keystone\n"
"Report-Msgid-Bugs-To: https://bugs.launchpad.net/keystone\n"
"POT-Creation-Date: 2014-10-07 06:05+0000\n"
"PO-Revision-Date: 2014-06-20 20:11+0000\n"
"Last-Translator: openstackjenkins <jenkins@openstack.org>\n"
"Language-Team: Japanese (http://www.transifex.com/projects/p/keystone/"
"language/ja/)\n"
"Language: ja\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Generated-By: Babel 1.3\n"
"Plural-Forms: nplurals=1; plural=0;\n"

#: keystone/notifications.py:176
#, python-format
msgid "Method not callable: %s"
msgstr ""

#: keystone/catalog/core.py:60
#, python-format
msgid "Malformed endpoint %(url)s - unknown key %(keyerror)s"
msgstr ""

#: keystone/catalog/core.py:65
#, python-format
msgid ""
"Malformed endpoint '%(url)s'. The following type error occurred during "
"string substitution: %(typeerror)s"
msgstr ""

#: keystone/catalog/core.py:71
#, python-format
msgid ""
"Malformed endpoint %s - incomplete format (are you missing a type notifier ?)"
msgstr ""

#: keystone/common/openssl.py:92
#, python-format
msgid "Command %(to_exec)s exited with %(retcode)s- %(output)s"
msgstr ""

#: keystone/common/openssl.py:120
#, python-format
msgid "Failed to remove file %(file_path)r: %(error)s"
msgstr ""

#: keystone/common/environment/eventlet_server.py:100
#, python-format
msgid "Could not bind to %(host)s:%(port)s"
msgstr ""

#: keystone/contrib/endpoint_policy/core.py:129
#: keystone/contrib/endpoint_policy/core.py:228
#, python-format
msgid ""
"Circular reference or a repeated entry found in region tree - %(region_id)s."
msgstr ""

#: keystone/contrib/federation/idp.py:405
#, python-format
msgid "Error when signing assertion, reason: %(reason)s"
msgstr ""

#: keystone/openstack/common/excutils.py:76
#, python-format
msgid "Original exception being dropped: %s"
msgstr "除去される元の例外: %s"

#: keystone/openstack/common/excutils.py:105
#, python-format
msgid "Unexpected exception occurred %d time(s)... retrying."
msgstr "予期せぬ例外が、%d回()発生しました。再試行中。"

#: keystone/openstack/common/loopingcall.py:95
msgid "in fixed duration looping call"
msgstr "一定期間の呼び出しループ"

#: keystone/openstack/common/loopingcall.py:138
msgid "in dynamic looping call"
msgstr "動的呼び出しループ"

#: keystone/openstack/common/policy.py:508
#, python-format
msgid "Failed to understand rule %s"
msgstr "ルール %s を解釈できませんでした"

#: keystone/openstack/common/policy.py:518
#, python-format
msgid "No handler for matches of kind %s"
msgstr "種類 %s の一致向けのハンドラーがありません"

#: keystone/openstack/common/policy.py:788
#, python-format
msgid "Failed to understand rule %r"
msgstr "ルール %r を解釈できませんでした"

#: keystone/openstack/common/service.py:188
msgid "Exception during rpc cleanup."
msgstr "RPCクリーンアップ中に例外が発生"

#: keystone/openstack/common/service.py:277
msgid "Unhandled exception"
msgstr "未処理例外"
